app1/urls.py
from django.conf.urls import url
from app1 import views

app_name = 'app1'
# made after making the app and on second step for app to have own urls.py
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'signup/', views.signup_view, name='signup'),
    url(r'^other/$', views.other, name='other'),
    url(r'^user_login/$', views.user_login, name='user_login'),
]

djangofirstone/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from app1 import views

# first added the views from app and also made separate app's url.py and reconfigured
urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^$', views.index, name='index'),
    path(r'app1/', include('app1.urls', namespace='app1')),
    url(r'^formpage/', views.loginform_view, name='form_name'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'special/', views.special, name='special'),
]

app1/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class UserprofileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.DO_NOTHING)

    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username


class Topic(models.Model):
    top_name = models.CharField(max_length=264, unique=True)

    def __str__(self):
        return self.top_name


class Webpage(models.Model):
    name = models.CharField(max_length=264, unique=True)
    topic = models.ForeignKey(Topic, on_delete=models.DO_NOTHING)
    url = models.URLField(unique=True)

    def __str__(self):
        return self.name


class AccessRecord(models.Model):
    name = models.ForeignKey(Webpage, on_delete=models.DO_NOTHING)
    date = models.DateField()

    def __str__(self):
        return str(self.date)

'''
class User(models.Model):
    name = models.CharField(max_length=264, unique=True)
    email = models.EmailField()
    site = models.ForeignKey(Webpage, on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.name
'''

app1/forms.py
from django import forms
from django.core import validators
from django.contrib.auth.models import User
from app1.models import UserprofileInfo

# build your custom validator

'''
def check_for_z(value):
    if value[0] .lower() != 'z':
        raise forms.ValidationError("name needs to start with z ")
'''


class Userform(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileInfoForm(forms.ModelForm):
    class Meta:
        model = UserprofileInfo
        fields = ('portfolio_site', 'profile_pic')


class LoginForm(forms.Form):
    name = forms.CharField()  #validators=[check_for_z])  # used custom validator
    email = forms.EmailField()
    verify_email = forms.EmailField(label="Enter your email again")
    text = forms.CharField(widget=forms.Textarea)
    botcatcher = forms.CharField(required=False,
                                 widget=forms.HiddenInput,
                                 validators=[validators.MaxLengthValidator(0)])

    # using a single clean for all variables
    def clean(self):
        all_clean_data = super().clean()
        email = all_clean_data['email']
        vmail = all_clean_data['verify_email']
        if email != vmail:
            raise forms.ValidationError("The emails don't match")

'''
    # use of single clean function
    # using clean_varname to create own validation. Done without using validator from core
    def clean_botcatcher(self):
        botcatcher = self.cleaned_data['botcatcher']
        if len(botcatcher) > 0:
            raise forms.ValidationError("You shitty bot")
        return botcatcher
'''


class Signup(forms.ModelForm):

    class Meta:
        model = User
        fields = "__all__"

app1/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
# from app1.models import Topic, Webpage, AccessRecord
from app1.forms import UserProfileInfoForm, Userform, LoginForm
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout

# Create your views here.


def index(request):
    """
    webpage_list = AccessRecord.objects.order_by('date')
    # my_dict = {'insert_me': "You are fucking bastard"}
    context_dict = {'text': 'hello world', 'number': 100}
    # date_dict = {'access_records': webpage_list}
    """
    return render(request, 'index.html')  # ,context=context_dict)


@login_required
def special(request):
    return HttpResponse("You are logged in")

@login_required()
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("account not  active")
        else:
            print("username and passwd don't match")
            return HttpResponse("invalid login details")
    else:
        return render(request, 'index.html')


def loginform_view(request):
    form = LoginForm()
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            print("Validated")
            print(form.cleaned_data['name'])
            print(form.cleaned_data['email'])
    return render(request, 'form_page.html', {'form': form})


def signup_view(request):
    registered = False
    if request.method == 'POST':
        user_form = Userform(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)
        if user_form.is_valid() and profile_form.is_valid():
            print("Validated")
            user = user_form.save()
            user.set_password(user.password)  # lecture 152
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']
            profile.save()
            registered = True
            return index(request)
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = Userform()
        profile_form = UserProfileInfoForm()

    return render(request, 'signup.html',
                  {'user_form': user_form,
                   'profile_form':profile_form,
                   'registered':registered})


def other(request):
    return render(request, 'app1/form.html')

templates/app1/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>This is a dummy page</title>
</head>
<body>
    <h1> Hello you are not fucked till now</h1>
</body>
</html>

templates/app1/login.html
<!DOCTYPE html>
{%  extends 'base.html' %}

{%  block hello_block %}
<div class="jumbotron">
    <h1> Please login</h1>
    <form method="post" action="{% url 'app1:user_ login' %}">
        {% csrf_token %}
        <label for="username"> Username: </label>
        <input type="text" name="username" placeholder="Enter username">
        <label for="password"> Password: </label>
        <input type="password" name="password">
        <input type="submit" name="" value="Login">
    </form>
</div>
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
          crossorigin="anonymous" />
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <ul class="nav navbar-nav">
                <li><a class="navbar-brand" href="{%  url 'index' %}">FORUM</a></li>
                <li><a class="navbar-link" href={%  url 'admin:index' %}>Admin</a></li>
                <li><a class="navbar-link" href={%  url 'app1:other' %}>Other</a></li>
                <li><a class="navbar-link" href={%  url 'app1:signup' %}>Register</a></li>

                {%  if user.is_authenticated %}
                    <li><a class="navbar-link" href="{%  url 'logout' %}">Logout</a></li>
                {%  else %}
                    <li><a class="navbar-link" href={% url 'app1:user_login' %}>Login</a></li>
                {% endif %}
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block hello_block %}
            <!-- Outside it is included -->
        {%  endblock %}

    </div>
</body>
</html>

templates/form_page.html
<!DOCTYPE html>
{%  load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login form</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u"
          crossorigin="anonymous" />
</head>
<h1> Put your login info</h1>
<body>
    <div class='container'>
        <form method="post">
            {{ form.as_p }}
            {%  csrf_token %}
            <input type="submit" class="btn btn-primary"  value="Submit">
        </form>
    </div>
</body>
</html>

templates/index.html
<!DOCTYPE html>
{%  extends "base.html" %}
{%  load staticfiles %}
{% block hello_block %}
    <link rel="stylesheet" href="{% static "css/mystyle.css" %}" />
    <h1> Hello Fucker Django</h1>
    <img src="{%  static "images/hello.jpg" %}" alt="oh shit!">
    <div class="bloody">
        {%  if access_records %}
            <table>
                <thead>
                    <th> Site name</th>
                    <th> Date accessed</th>
                </thead>
            {%  for acc in access_records %}
                <tr>
                    <td>{{ acc.name }}</td>
                    <td>{{ acc.date }}</td>
                </tr>
            {% endfor %}
            </table>
        {% else %}
            {{ text | cut:'hello' }}
            {{ number | add:'99' }}
            <p>"You are fucked buddy</p>
        {% endif %}
    </div>
    <h2> Go and fuck yourself soon </h2>
{%  endblock %}

templates/signup.html
<!DOCTYPE html>
{%  extends 'base.html' %}
    {%  block hello_block %}
        <div class="jumbotron">
            <h1> Welcome to IOE forum</h1>
            {%  if registered %}
                <h1> Thank you for registering your name</h1>
            {% else %}
                <h1> Register here</h1>
                <h3> Fill out the form</h3>
                <form method="post" enctype="multipart/form-data">
                    {{ user_form.as_p }}
                    {{ profile_form.as_p }}
                    {%  csrf_token %}
                    <input type='submit' class="btn btn-primary" value="Register">
                </form>
            {% endif %}
        </div>
    {% endblock %}